name: pipeline

on:
  push:

jobs:
  my-job:
    runs-on: ubuntu-latest
    with:
        distribution: temurin
        java-version: 11

    steps:
      - uses: actions/checkout@v3

      - name: execute program
        run: ./gradlew run