name: devops practice pipeline

on:
    push:

jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
            uses: actions/checkout@v3
            - run: ./gradlew run 